# Based on Bitbucket's sample build configuration for Java (Maven).
# Check out the guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
#
# IMPORTANT! Only use spaces to indent your .yml configuration!

# Use the most recent maven docker image from Docker Hub as the build environment,
# specifically using OpenJDK 8.
image: maven:3.9.8-eclipse-temurin-17

pipelines:
  default:
    # This build runs automatically for all commits
    - step:
        name: Build and Test
        caches:
          - maven # predefined; caches ~/.m2/repository
        script:
          - apt update && apt install -y libgomp1
          - mvn -B verify # -B batch mode makes Maven less verbose
  pull-requests:
    # This build runs automatically for pull requests, running
    # full tests (including ITs) on the merged branches
    '**':
      - step:
          name: Build and Test
          max-time: 30
          caches:
            - maven
          script:
            - apt update && apt install -y libgomp1
            - mvn -B verify -DskipITs=false
  tags:
    # This build runs automatically but only on tagged encyclopedia releases
    encyclopedia-*:
      - step:
          name: Build and Test
          max-time: 30
          caches:
            - maven # predefined; caches ~/.m2/repository
          script:
            # Similar to above, but with encyclopedia executable JAR and ITs
            # We also deploy the resulting attached artifacts, which (importantly)
            # includes the regression test reference data that was generated.
            - apt update && apt install -y libgomp1
            - mvn -B verify deploy -PbuildEncyclopedia -DskipITs=false
          artifacts:
            # Defines the file(s) to be saved for use in the next step
            - target/encyclopedia-*-executable.jar
      - step:
          name: Deploy
          script:
            # Upload file as a download to the repo
            - pipe: atlassian/bitbucket-upload-file:0.3.0
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: 'target/encyclopedia-*-executable.jar'
      - step:
          name: Push to Dockerhub
          script:
            # Get current version number
            - export VERSION=${BITBUCKET_TAG/encyclopedia-/}
            - export IMAGE_NAME=searlelab/encyclopedia
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t $IMAGE_NAME:$VERSION --build-arg VERSION=$VERSION .
            - docker push $IMAGE_NAME:$VERSION
          services:
            - docker

  custom:
    # This custom build allows manual triggering of
    # integration tests on any commit
    integration-tests:
      - step:
          name: Build and Test
          max-time: 30
          caches:
            - maven
          script:
            - apt update && apt install -y libgomp1
            - mvn -B verify -DskipITs=false
    # This custom build allows manual deployment of
    # Maven artifacts from any commit; this is useful
    # for regression test data generation and deployment.
    # It does NOT build or deploy executable versions
    # or upload anything to the Bitbucket repository.
    # Note that this build IGNORES TEST FAILURES on the
    # assumption that they're the result of regression
    # failures. It's important to only trigger this
    # build on well-vetted commits, and to understand
    # usages of the deployed artifacts.
    deploy-maven-artifacts:
      - step:
          name: Build, Test and Deploy
          max-time: 30
          caches:
            - maven
          script:
            - apt update && apt install -y libgomp1
            - mvn -B verify deploy -DskipITs=false -Dmaven.test.failure.ignore=true

options:
  # All steps use a default time out after 15 minutes to
  # avoid wasting build minutes. If IT execution grows to
  # exceed this limit, it's best to add relaxed timeouts
  # to the specific step(s) that run too long.
  max-time: 15
