# Based on Bitbucket's sample build configuration for Java (Maven).
# Check out the guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
#
# IMPORTANT! Only use spaces to indent your .yml configuration!

# Use the most recent maven docker image from Docker Hub as the build environment,
# specifically using OpenJDK 8.
image: maven:3.6.3-openjdk-8

pipelines:
  default:
    - step:
        caches:
          - maven # predefined; caches ~/.m2/repository
        script:
          - mvn -B verify # -B batch mode makes Maven less verbose
  tags:
    # this build only runs on tagged encyclopedia releases
    encyclopedia-*:
      - step:
          caches:
            - maven # predefined; caches ~/.m2/repository
          script:
            # Similar to above, but with encyclopedia executable JAR and ITs
            - mvn -B package verify -PbuildEncyclopedia -DskipITs=false
            # Upload file as a download to the repo
            - pipe: atlassian/bitbucket-upload-file:0.3.0
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: 'target/encyclopedia-*-executable.jar'
