package edu.washington.gs.maccoss.encyclopedia.utils.massspec;

import java.util.ArrayList;

import edu.washington.gs.maccoss.encyclopedia.datastructures.AminoAcidConstants;
import edu.washington.gs.maccoss.encyclopedia.datastructures.FastaEntry;
import edu.washington.gs.maccoss.encyclopedia.datastructures.FastaPeptideEntry;
import edu.washington.gs.maccoss.encyclopedia.datastructures.ModificationMassMap;
import gnu.trove.map.hash.TCharDoubleHashMap;
import junit.framework.TestCase;

public class ExtendedDigestionEnzymeTest extends TestCase {
	private static final DigestionEnzyme enzyme=DigestionEnzyme.getEnzyme("Trypsin");
	public void testAAAAAARLNR() {
		String sequence="MRHSLTKLLAASGSNSPTRSESPEPAATCSLPSDLTRAAAGEEETAAAGSPGRKQQFGDEGELEAGRGSRGGVAVRAPSPEEMEEEAIASLPGEETEDMDFLSGLELADLLDPRQPDWHLDPGLSSPGPLSSSGGGSDSGGLWRGDDDDEAAAAEMQRFSDLLQRLLNGIGGCSSSSDSGSAEKRRRKSPGGGGGGGSGNDNNQAATKSPRKAAAAAARLNRLKKKEYVMGLESRVRGLAAENQELRAENRELGKRVQALQEESRYLRAVLANETGLARLLSRLSGVGLRLTTSLFRDSPAGDHDYALPVGKQKQDLLEEDDSAGGVCLHVDKDKVSVEFCSACARKASSSLKM";
		String target="AAAAAARLNR";
		
		ArrayList<FastaPeptideEntry> set=enzyme.digestProtein(new FastaEntry(sequence), 5, 40, 1, new AminoAcidConstants(new TCharDoubleHashMap(), new ModificationMassMap()));
		boolean found=false;
		for (FastaPeptideEntry peptide : set) {
			if (target.equals(peptide.getSequence())) {
				found=true;
				break;
			}
		}
		assertTrue(found);
	}

	public void testAAVRETHK() {
		String sequence="MAEADFKMVSEPVAHGVAEEEMASSTSDSGEESDSSSSSSSTSDSSSSSSTSGSSSGSGSSSSSSGSTSSRSRLYRKKRVPEPSRRARRAPLGTNFVDRLPQAVRNRVQALRNIQDECDKVDTLFLKAIHDLERKYAELNKPLYDRRFQIINAEYEPTEEECEWNSEDEEFSSDEEVQDNTPSEMPPLEGEEEENPKENPEVKAEEKEVPKEIPEVKDEEKEVPKEIPEVKAEEKADSKDCMEATPEVKEDPKEVPQVKADDKEQPKATEAKARAAVRETHKRVPEERLQDSVDLKRARKGKPKREDPKGIPDYWLIVLKNVDKLGPMIQKYDEPILKFLSDVSLKFSKPGQPVSYTFEFHFLPNPYFRNEVLVKTYIIKAKPDHNDPFFSWGWEIEDCKGCKIDWRRGKDVTVTTTQSRTTATGEIEIQPRVVPNASFFNFFSPPEIPMIGKLEPREDAILDEDFEIGQILHDNVILKSIYYYTGEVNGTYYQFGKHYGNKKYRK";
		String target="AAVRETHK";
		ArrayList<FastaPeptideEntry> set=enzyme.digestProtein(new FastaEntry(sequence), 5, 40, 1, new AminoAcidConstants(new TCharDoubleHashMap(), new ModificationMassMap()));
		boolean found=false;
		for (FastaPeptideEntry peptide : set) {
			if (target.equals(peptide.getSequence())) {
				found=true;
				break;
			}
		}
		assertTrue(found);
	}
	
	public void testAAACPSSPHK() {
		String sequence="MSSQTKFKKDKEIIAEYEAQIKEIRTQLVEQFKCLEQQSESRLQLLQDLQEFFRRKAEIELEYSRSLEKLAERFSSKIRSSREHQFKKDQYLLSPVNCWYLVLHQTRRESRDHATLNDIFMNNVIVRLSQISEDVIRLFKKSKEIGLQMHEELLKVTNELYTVMKTYHMYHAESISAESKLKEAEKQEEKQFNKSGDLSMNLLRHEDRPQRRSSVKKIEKMKEKRQAKYSENKLKCTKARNDYLLNLAATNAAISKYYIHDVSDLIDCCDLGFHASLARTFRTYLSAEYNLETSRHEGLDVIENAVDNLDSRSDKHTVMDMCNQVFCPPLKFEFQPHMGDEVCQVSAQQPVQTELLMRYHQLQSRLATLKIENEEVRKTLDATMQTLQDMLTVEDFDVSDAFQHSRSTESVKSAASETYMSKINIAKRRANQQETEMFYFTKFKEYVNGSNLITKLQAKHDLLKQTLGEGERAECGTTRPPCLPPKPQKMRRPRPLSVYSHKLFNGSMEAFIKDSGQAIPLVVESCIRYINLYGLQQQGIFRVPGSQVEVNDIKNSFERGEDPLVDDQNERDINSVAGVLKLYFRGLENPLFPKERFQDLISTIKLENPAERVHQIQQILVTLPRVVIVVMRYLFAFLNHLSQYSDENMMDPYNLAICFGPTLMHIPDGQDPVSCQAHINEVIKTIIIHHEAIFPSPRELEGPVYEKCMAGGEEYCDSPHSEPGAIDEVDHDNGTEPHTSDEEVEQIEAIAKFDYMGRSPRELSFKKGASLLLYHRASEDWWEGRHNGVDGLIPHQYIVVQDMDDAFSDSLSQKADSEASSGPLLDDKASSKNDLQSPTEHISDYGFGGVMGRVRLRSDGAAIPRRRSGGDTHSPPRGLGPSIDTPPRAAACPSSPHKIPLTRGRIESPEKRRMATFGSAGSINYPDKKALSEGHSMRSTCGSTRHSSLGDHKSLEAEALAEDIEKTMSTALHELRELERQNTVKQAPDVVLDTLEPLKNPPGPVSSEPASPLHTIVIRDPDAAMRRSSSSSTEMMTTFKPALSARLAGAQLRPPPMRPVRPVVQHRSSSSSSSGVGSPAVTPTEKMFPNSSADKSGTM";
		String target="AAACPSSPHK";
		ArrayList<FastaPeptideEntry> set=enzyme.digestProtein(new FastaEntry(sequence), 5, 40, 1, new AminoAcidConstants(new TCharDoubleHashMap(), new ModificationMassMap()));
		boolean found=false;
		for (FastaPeptideEntry peptide : set) {
			if (target.equals(peptide.getSequence())) {
				found=true;
				break;
			}
		}
		assertTrue(found);
	}
	
}
